baseURL: https://nafuka11.github.io/
languageCode: en-us
title: nafuka11.github.io
theme: PaperMod

params:
  profileMode:
    enabled: true
    title: nafuka11
    subtitle: "A student at [42Tokyo](https://42tokyo.jp/)."
    imageUrl: /icon.jpg
    buttons:
      - name: Resume
        url: /resume
      - name: Works
        url: /works

  socialIcons:
    - name: twitter
      url: https://twitter.com/nafuka11
    - name: github
      url: https://github.com/nafuka11
    - name: rss
      url: https://nafuka.hatenablog.com/

menu:
  main:
    - identifier: resume
      name: Resume
      url: /resume/
      weight: 10
    - identifier: works
      name: Works
      url: /works/
      weight: 20
